# Generated by Django 2.2.6 on 2019-10-04 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='realtor',
            name='district',
            field=models.TextField(blank=True),
        ),
    ]
