# Generated by Django 2.2.6 on 2019-10-15 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0002_auto_20191011_0855'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='text',
            new_name='comments',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
    ]
