# Generated by Django 2.2.6 on 2019-10-05 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0002_realtor_district'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='realtor',
            options={'verbose_name': 'Realtor'},
        ),
    ]
