# Generated by Django 2.2.6 on 2019-10-15 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0003_auto_20191015_0939'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comments',
            new_name='comment',
        ),
    ]
