# Generated by Django 2.2.6 on 2019-10-05 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0003_auto_20191005_0300'),
    ]

    operations = [
        migrations.RenameField(
            model_name='realtor',
            old_name='owner_name',
            new_name='owner',
        ),
    ]
