# Generated by Django 2.2.6 on 2019-10-16 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0004_auto_20191015_0942'),
    ]

    operations = [
        migrations.RenameField(
            model_name='realtor',
            old_name='district',
            new_name='details',
        ),
    ]
