# Generated by Django 2.2.6 on 2019-10-05 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0006_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='created_date',
        ),
    ]
