# Generated by Django 2.2.6 on 2019-10-11 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0008_auto_20191011_0638'),
    ]

    operations = [
        migrations.RenameField(
            model_name='realtor',
            old_name='create_date',
            new_name='created_date',
        ),
    ]
